services:
  frontend:
    build:
      context: ./nextjs-docker
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db